config/routes.rb
Rails.application.routes.draw do

  root 'main#index'
  resources :teachers, :only => [:index, :create, :new, :edit, :update, :destroy]
  resources :courses, :only => [:index, :create, :new, :edit, :update, :destroy]
  resources :users, :only => [:index, :create, :new, :edit, :update, :destroy]

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :teacher
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :courses, :dependent => :destroy
  has_many :students, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :courses, :dependent => :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

	def index
		@courses = Course.all
	end

	def new
		@course = Course.new
	end

	def edit
		@course = Course.find(params[:id])
	end

	def create
		@course = Courses.new(course_params)
		if @course.save
			message = 'Your lesson has been successfully created.'
			redirect_to edit_course_url(@course.id), :fash => {:success => message}
		else
			message  = 'Please correct these errors: #{@course.errors.full)messages.join(', ')}'
			flash.now[:error] = message
			render 'courses/new'
		end
	end

	def update
		@course = Course.find(params[:id])
		@course.assign_attributes(course_params)

		if @course.save
			message = 'Your changes have been saved.'
			redirect_to edit_course_url(@course.id), :flash => {:success => message}
		else
			message = 'Please correct these errors: #{@course.errors.full_messages.join(', ')}'
			flash.now[:error] = message
			renger 'courses/edit'
		end
	end

	def destroy
		@course = Course.find(params[:id])
		@course.destroy

		respond_to do |f|
			f.html { redirect_to courses_url }
			f.json { render :json => {} }
		end
	end

	private
	# add: teacher_id, duration, start_time, name
	# remove: full_name
	def course_params
		params.require(:course).permit(:full_name)
	end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

	def index
		@teachers = Teacher.all
	end

	def new
		@teacher = Teacher.new
	end
	
	def edit
		@teacher = Teacher.find(params[:id])
	end

	def create
		@teacher = Teacher.new(teacher_params)
		if @teacher.save
			message = 'Success! Your teacher has been saved.'
			#redirect_to edit_teacher_url(@teacher.id), :flash => {:success => message}
			redirect_to teachers_url, :flash => {:success => message}
		else
			message = 'Please correct these errors: #{@teacher.errors.full)messages.join(', ')}'
			flash.now[:error] = message
			render 'teachers/new'
		end
	end

	def update
		@teacher = Teacher.find(params[:id])
		@teacher.assign_attributes(teacher_params)

		if @teacher.save
			message = 'Success! Your changes have been saved.'
			redirect_to edit_teacher_url(@teacher.id), :flash => {:success => message}
		else
			message = 'Please correct these errors: #{@teacher.errors.full_messages.join(', ')}'
			flash.now[:error] = message
			render 'teachers/edit'
		end
	end

	def destroy
		@teacher = Teacher.find(params[:id])
		@teacher.destroy

		respond_to do |f|
			f.html { redirect_to teachers_url }
			f.json { render :json => {} }
		end
	end

	private

	def teacher_params
		params.require(:teacher).permit(:full_name)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def edit
		@user = User.fine(params[:id])
	end

	def create
		@user = User.new(user_params)
		if @user.save
			message = 'Success! Your account has been created.'
		else
			message = 'Please correct these errors: #{@user.errors.full)messages.join(', ')}'
			flash.now[:error] = message
			render 'users/new'
		end
	end

	def update
		@user = User.find(paramds([:id])
		@user.assign_attributes(user_params)

		if @user.save
			message = 'Success! Your changes have been saved.'
			redirect to edit_user_url(@user.id), flash => {:success =>message}
		else
			message = 'Please correct these errors: #{@user.errors.full_message.join(', ')}'
			flash.now[:error] = message
			render 'users/edit'
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy

		respond_to do |f|
			f.html { redirect_tp users_url }
			f.json { render :json => {} }
		end
	end

	private

	def user_params
		params.require(:user).permit(:full_name, :email, :birth_date, :phone_number)
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/_form.html.erb
<%# %>


	<%= form_for :course do |f| %>

		
		<%= f.label :class_name %>
		<%= f.text_field :class_name %>
		<%= f.label :start_time %>
		<%= f.text_field :start_time %>
		<%= f.label :duration %>
		<%= f.integer :duration %>

		<%= f.submit "Submit", f.disable_with "Submitting.." %>


	<% end %>
		

app/views/courses/edit.html.erb
<%= render partial: 'form' %>
<%# %>

app/views/courses/index.html.erb
<%# %>


<% @courses.each do |f| %>
	<div><%= f.course.class_name %></div>

<% end %>

app/views/courses/new.html.erb
<%= render partial: 'form' %>

<%# %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AstaireLv</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<p>
Hi, this is the new homepage.

<%# link to users, courses, and teachers %>

<% link_to 'Create New Teacher',new_teacher_path, class: 'button' %>
</p>

app/views/teachers/_form.html.erb
<%# in app/views/teachers/_form %>

<%# teacher_param %>

<h1> Create new teacher </h1>
<%= form_for @teacher  do |f| %>
<%# how to add :url correctly? %>
	<p>
		<%= f.label :full_name %>
		<%= f.text_field :full_name %>
		<%= f.submit "Submit" %>
	</p>
<% end %>

app/views/teachers/edit.html.erb
<%= render partial: 'form' %>

app/views/teachers/index.html.erb
<%# in app/views/teachers/index %>

<%#list all available teachers%>
<h1> List of current teachers:</h1>
<% @teachers.each do |f| %>
	<div><%= f.full_name %></div>
<% end %>


<%# add link to creating new teacher %>
<%# add link to search existing teachers %>

app/views/teachers/new.html.erb
<%= render partial: 'form' %>

app/views/users/_form.html.erb
<%# comment %>

<%#user form%>

<h1> New user information</h1>
<%= form_for :user do |f| %>
<%#probably still need to add :url %>
	<p>
		<%= f.label :full_name %>
		<%= f.text_field :full_name %>
		<%= f.label :birth_date %>
		<%= f.datetime :birth_date %>
		<%= f.label :phone_number %>
		<%= f.text_field :phone_number %>
		<%= f.label :email %>
		<%= f.text_field :email %>



		<%= f.submit "Submit", f.disable_with "Submitting.." %>
		<%# need to add button near the bottom for 'Accept T&C' and 'Accept PPolicy' that has a link as well that's aligned differently <%>

		</p>
	<% end %>

app/views/users/edit.html.erb
<%= render partial: 'form' %>

<%# %>

app/views/users/index.html.erb
<%# %>
<%# in app/views/teachers/index %>

<%#list all available teachers%>
<% @users.each do |f| %>
	<div><%= f.user.full_name %></div>
	<%# need to add something more significant to differentiate between students if similar names %>
	<%# picture? age? %>

<% end %>

<%# add link to creating new teacher %>
<%# add link to search existing teachers %>

app/views/users/new.html.erb
<%# %>

<%= render partial: 'form' %>